# ===================================================================
# APPLICATION PROPERTIES
# ===================================================================
spring:
  application:
    name: inventory-service
---
# ===================================================================
# Default / Localhost PROPERTIES
# ===================================================================
spring:
  profiles: default
server:
  port: 8090
---
# ===================================================================
# Production PROPERTIES
# ===================================================================
spring:
  profiles: production
server:
  port: 8080
